-- The single consumer-visible identity of the derived assets crossing the
-- romdump boundary: cache formats, generated schemas, and binary format
-- versions. Producers and runtime read these constants through the libs/assets
-- cache modules rather than carrying their own literals, so a format change is
-- one edit. `revision` is the manual escape hatch for a shared contract
-- behavior change that alters generated bytes without changing any schema
-- constant; compiler implementation versions are deliberately absent (producer
-- freshness belongs to the romdump source fingerprint).
--
-- revision 2: the compiled NSBTP payload drops the redundant
-- keyCount/numTextures/numPalettes counts (sampler and gate trust the
-- arrays).
--
-- map sceneSchema 7: map/neighbor terrain batches can now serialize
-- alphaClass = "mixed" (AlphaClassifier v2: a MODULATE polygon at alpha 31
-- with both opaque and partial texture alpha texels splits into an opaque
-- and a translucent subpass instead of being forced wholly translucent).
--
-- fieldActors schema 2: the visual definition's render.alphaClass now comes
-- from AlphaClassifier v2 (polygon-mode-aware, final-alpha-driven
-- classification); the vocabulary a stale v1 cache could have baked in is
-- no longer trustworthy.
--
-- fieldActors index 3: the runtime avatar capability is a semantic state map.
-- Each playable gender carries exactly the fourteen visual states with
-- compiled sprite IDs, so runtime state transitions resolve any visual
-- without source interpretation or fallback. A stale index without the state
-- maps must fail readiness; only the index identity changes.
--
-- fieldActors schema 3/cache v2: generated visuals carry the required
-- source-independent idle presentation profile and the required semantic
-- gesture clip map. Each idle pose segment carries a finite
-- displayOffsetY required for phase-correct presentation, and each visual
-- carries a required gestures table. Non-empty semantic gesture clips belong
-- to atlas/billboard visuals with validated poses and finite display offsets
-- for the supported sprite-specific clips (nurse_bow, give, receive); static
-- models require the empty gesture table because the current static
-- presentation has no gesture frame selection. A stale visual cannot supply
-- the actor's idle cadence, display offsets, or gesture presentation safely.
--
-- fieldUi schema 6: wayfinding rects become final 48x32 surfaces. Each
-- (type, map) rect is a 6x4 arrangement (48px wide, 32px tall) composed at
-- build time from the original 24 8x8 tiles, instead of a raw 192x8 strip.
--
-- fieldUi schema 5: signposts.types entries gain per-type palette banks
-- (one 16-color table per source type) and per-type frameTiles rectangles.
-- The old global signposts.frame.tiles authority is removed. Each type's
-- frame strip uses its own palette for precolored rendering. signposts
-- gains textColors (the foreground/shadow/background palette slots), so
-- text rendering no longer has to hardcode the source's fixed 2/10/15 slots.
--
-- fieldUi schema 4: the manifest drops the per-frame dialogueFrames.palettes
-- records (the palette colors are baked into the compiled frame-strip PNG;
-- no runtime consumer exists).
--
-- fieldUi schema 3: signpost wayfinding becomes a per-(type,map) rect table
-- (signposts.types[N].wayfinding[map]) and the manifest drops the
-- startMenu.icons mapping (no runtime consumer remains; the icon art is
-- baked into the background surface).
--
-- fieldUi schema 2: the generated field-UI manifest drops the sounds
-- section (the branch no longer compiles Start Menu effects).
--
-- messages cacheFormat v2: YESNO tokens classify as focus_indicator in the
-- persisted bank streams (runtime playback rejects the old
-- unsupported_control classification), so a stale bank must not be misread.
--
-- font cacheFormat/schema v2: the compiled definition gains seven color bands
-- and a focus-indicator PNG, and the marker hashes font member 6, so a stale
-- pre-change font cache must not pass readiness.
-- intro OBJ geometry: animated widgets retain one OAM-origin pivot across
-- frames and publish source-reference centers for responsive placement.
-- field map schema 9: generated object events publish semantic movement types
-- instead of raw HGSS movement selectors.

local DerivedAssetContract = {}

DerivedAssetContract.revision = 10

DerivedAssetContract.map = {
  cacheFormat = "map-cache-v7",
  -- v9: neighboring matrix cells carry required normalized X/Y/Z placement;
  -- runtime consumers preserve the source-relative vertical placement.
  -- v6: render-state extension over v5 — scenes carry the real HGSS field
  -- edge-color table (scene.edgeColors), every batch/material record carries
  -- the per-polygon fog gate (fogEnabled, PolygonState.FIELDS), and scenes
  -- carry the map's base weather ID plus its resolved global HGSS fog preset
  -- (scene.weatherId, scene.fog).
  sceneSchema = "g4-map-scene-v9",
  terrainSchema = "g4-terrain-surfaces-v1",
  collisionVersion = 1,
}

DerivedAssetContract.fieldCells = {
  cacheFormat = "field-cell-cache-v2",
  indexSchema = "g4-field-cell-index-v2",
  cellSchema = "g4-field-cell-v2",
}

DerivedAssetContract.fieldActors = {
  cacheFormat = "field-actor-cache-v2",
  schema = "g4-field-actor-v3",
  indexSchema = "g4-field-actor-index-v3",
}

DerivedAssetContract.fieldCamera = {
  cacheFormat = "g4-field-camera-cache-v1",
  schema = "g4-field-camera-profiles-v1",
}

DerivedAssetContract.fieldMapData = {
  cacheFormat = "g4-field-map-cache-v1",
  -- The generated field record carries the day/night map-header music block
  -- as canonical audio sequence references (never bare source suffixes), so
  -- the runtime field-music policy reads it directly and never decorates
  -- symbols. v5 drops the source-only volumeIndex from the soundplates
  -- records: the BGM duck and ambient targets derived from the raw volume
  -- index are emitted instead (nothing above index two), the disable flag
  -- comes from the frozen reference rule scoped to the map, and raw
  -- soundplateSoundID never reaches the record. v4 added the flag/traversal
  -- music policy and the semantic soundplates array to the record.
  -- v7 makes initScripts a strict source-independent descriptor union. v8
  -- normalizes the retail unbound-script marker (0xFFFF) to zero so runtime
  -- binding and interaction audits never interpret raw ROM data. v9
  -- publishes semantic object movement types instead of raw HGSS selectors.
  fieldSchema = "g4-field-map-v9",
}

DerivedAssetContract.messages = {
  cacheFormat = "field-message-cache-v3",
  schema = "g4-field-message-bank-v1",
  indexSchema = "g4-field-message-index-v1",
  provenanceSchema = "g4-field-message-provenance-v1",
}

-- v4: the font class requires font IDs 0 and 4 in one atomic publication;
-- v3: the font class gains a required semantic glyph mask atlas (categorical
-- foreground/shadow/background classes, distinct from the composited RGB
-- atlas) so palette-driven presentation can recolor glyphs against an
-- arbitrary runtime palette instead of the font's own baked color bands.
DerivedAssetContract.font = {
  cacheFormat = "field-font-cache-v4",
  schema = "g4-field-font-v3",
}

DerivedAssetContract.scripts = {
  cacheFormat = "script-cache-v2",
  indexSchema = "g4-script-index-v1",
  provenanceSchema = "g4-script-provenance-v1",
}

DerivedAssetContract.fieldWeather = {
  cacheFormat = "field-weather-cache-v1",
  schema = "g4-field-weather-v1",
}

DerivedAssetContract.newGameInit = {
  cacheFormat = "g4-new-game-init-cache-v1",
  schema = "g4-new-game-init-v2",
}

DerivedAssetContract.fieldEffects = {
  -- v8 carries the persistent surf attachment and the follower-transition
  -- effect alongside the existing grass hold and trainer reveal definitions.
  cacheFormat = "field-effect-cache-v8",
  indexSchema = "g4-field-effect-index-v2",
}

DerivedAssetContract.fieldEmotes = {
  cacheFormat = "field-emotes-cache-v2",
  schema = "g4-field-emote-v1",
}

DerivedAssetContract.fieldUi = {
  cacheFormat = "field-ui-cache-v1",
  schema = "g4-field-ui-v7",
}

DerivedAssetContract.intro = {
  cacheFormat = "intro-cache-v10",
  schema = "g4-intro-assets-v10",
  provenanceSchema = "g4-intro-provenance-v1",
}

-- The mon class carries the complete species/form/move/ability/growth
-- catalog plus the party-icon and portrait atlases with their selection
-- manifests. Following-mon drawable definitions stay in the field-actor
-- class; the catalog references field-actor visual IDs only.
DerivedAssetContract.mons = {
  cacheFormat = "mon-cache-v1",
  -- v2 adds the generated item collection: one strict
  -- { nativeId, isBall, friendshipBoost } record per source native item
  -- identity 0..536, the single runtime source for item numbering.
  catalogSchema = "g4-mon-catalog-v2",
  indexSchema = "g4-mon-index-v1",
  iconManifestSchema = "g4-mon-icon-manifest-v1",
  portraitManifestSchema = "g4-mon-portrait-manifest-v1",
}

DerivedAssetContract.audio = {
  cacheFormat = "g4-audio-cache-v1",
  -- The index carries the per-class symbol maps sequenceBySymbol and
  -- bankBySymbol (wave-archive symbols are not indexed), per-player entries
  -- with only runtime-relevant fields (the parser keeps source facts such as
  -- the heap budget), and no stored payload path on sequence/bank records:
  -- every path derives from the numeric id (AudioCache.sequencePath/bankPath),
  -- so a redundant `file` field is malformed index data.
  indexSchema = "g4-audio-index-v5",
  -- The sequence asset carries a closed semantic instruction vocabulary and
  -- the NNS initial-volume domain; v9 rejects values above 0x7F.
  sequenceSchema = "g4-audio-sequence-v9",
  -- v5 includes exact silent DUMMY leaves and the 0xFF release sentinel.
  bankSchema = "g4-audio-bank-v5",
  sampleSchema = "g4-audio-sample-v4",
  provenanceSchema = "g4-audio-provenance-v1",
}

-- The mesh batch format constants (magic, version, stride, header size,
-- index widths) have their own owner (G4MeshFormat); the vertex-layout
-- version aliases that owner's version, so nothing mesh-shaped lives here.

return DerivedAssetContract
